-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tb_favoritar
(
    id_favorito serial NOT NULL,
    updated_at timestamp without time zone,
    created_at timestamp without time zone,
    id_receita integer NOT NULL,
    id_usuario integer NOT NULL,
    CONSTRAINT tb_favoritar_pkey PRIMARY KEY (id_favorito)
);

CREATE TABLE IF NOT EXISTS public.tb_receita
(
    id_receita serial NOT NULL,
    titulo_receita character varying(100) COLLATE pg_catalog."default" NOT NULL,
    origem_receita character varying(255) COLLATE pg_catalog."default" NOT NULL,
    url_imagem character varying(255) COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    id_usuario integer NOT NULL,
    CONSTRAINT tb_receita_pkey PRIMARY KEY (id_receita)
);

CREATE TABLE IF NOT EXISTS public.tb_usuario
(
    id_usuario serial NOT NULL,
    nome character varying COLLATE pg_catalog."default" NOT NULL,
    nome_usuario character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default" NOT NULL,
    senha character varying COLLATE pg_catalog."default" NOT NULL,
    imagem_usuario bytea,
    tipo tipo NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT tb_usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.tb_favoritar
    ADD CONSTRAINT fk_receita FOREIGN KEY (id_receita)
    REFERENCES public.tb_receita (id_receita) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tb_favoritar
    ADD CONSTRAINT fk_usuario FOREIGN KEY (id_usuario)
    REFERENCES public.tb_usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tb_receita
    ADD CONSTRAINT fk_usuario FOREIGN KEY (id_usuario)
    REFERENCES public.tb_usuario (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;